import{useMemo,useState}from'react';import{CalendarDays,CheckCircle2,FolderKanban,Home,Plus,Search,Sparkles,Tasks,ChevronLeft,Clock}from'lucide-react';
type Project={id:number;name:string;stage:string};type Task={id:number;title:string;projectId:number;due:string;done:boolean};
const projects:Project[]=[{id:1,name:'חיפה – מתחם מגורים',stage:'ביצוע'},{id:2,name:'נהריה – מגדלים',stage:'תכנון'},{id:3,name:'רמת השרון',stage:'ביצוע'},{id:4,name:'קריות – התחדשות',stage:'תכנון'}];
const initial:Task[]=[{id:1,title:'בדיקה כלכלית לפרויקט',projectId:1,due:'היום',done:false},{id:2,title:'לעבור על לוח זמנים מעודכן',projectId:3,due:'היום',done:false},{id:3,title:'אישור חשבון חודשי',projectId:2,due:'השבוע',done:false},{id:4,title:'סיכום סטטוס תכנון',projectId:4,due:'באיחור',done:false}];
export default function App(){const[tab,setTab]=useState('today');const[tasks,setTasks]=useState(initial);const[add,setAdd]=useState(false);const[title,setTitle]=useState('');const[pid,setPid]=useState(1);const open=useMemo(()=>tasks.filter(t=>!t.done),[tasks]);const save=()=>{if(!title.trim())return;setTasks(x=>[{id:Date.now(),title:title.trim(),projectId:pid,due:'היום',done:false},...x]);setTitle('');setAdd(false)};
return <div className="app"><header><div><small>יום שלישי · 6 באוקטובר</small><h1>{tab==='today'?'היום שלי':tab==='tasks'?'משימות':tab==='projects'?'פרויקטים':'העוזר שלי'}</h1></div><button className="avatar">י</button></header><main>
{tab==='today'&&<><section className="hero"><div><span>בוקר טוב</span><strong>{open.length} משימות פתוחות</strong></div><CalendarDays/><p>היום שלך מרוכז במקום אחד — פגישות, משימות ודברים שדורשים תשומת לב.</p></section><Section title="דורש טיפול" count={open.filter(t=>t.due==='באיחור').length}>{open.filter(t=>t.due==='באיחור').map(t=><TaskRow key={t.id} t={t} projects={projects} done={()=>setTasks(a=>a.map(x=>x.id===t.id?{...x,done:true}:x))}/>)}</Section><Section title="להיום" count={open.filter(t=>t.due==='היום').length}>{open.filter(t=>t.due==='היום').map(t=><TaskRow key={t.id} t={t} projects={projects} done={()=>setTasks(a=>a.map(x=>x.id===t.id?{...x,done:true}:x))}/>)}</Section></>}
{tab==='tasks'&&<><div className="search"><Search size={18}/><input placeholder="חיפוש משימה או פרויקט"/></div><Section title="כל המשימות" count={open.length}>{open.map(t=><TaskRow key={t.id} t={t} projects={projects} done={()=>setTasks(a=>a.map(x=>x.id===t.id?{...x,done:true}:x))}/>)}</Section></>}
{tab==='projects'&&<div className="grid">{projects.map(p=>{const n=open.filter(t=>t.projectId===p.id).length;return <article className="project" key={p.id}><div className="projectIcon"><FolderKanban/></div><span>{p.stage}</span><h3>{p.name}</h3><p>{n} משימות פתוחות</p><div className="projectFoot">פתיחת פרויקט <ChevronLeft size={17}/></div></article>})}</div>}
{tab==='ai'&&<div className="ai"><Sparkles size={34}/><h2>העוזר שלי</h2><p>בהמשך אוכל לסכם מסמכים, לאתר החלטות ולתת תמונת מצב מכל פרויקט.</p>{['מה דחוף השבוע?','תן לי תמונת מצב של פרויקט חיפה','אילו החלטות עדיין פתוחות?'].map(x=><button key={x}>{x}</button>)}</div>}
</main><nav><Nav active={tab==='today'} icon={<Home/>} label="היום" onClick={()=>setTab('today')}/><Nav active={tab==='tasks'} icon={<CheckCircle2/>} label="משימות" onClick={()=>setTab('tasks')}/><button className="fab" onClick={()=>setAdd(true)}><Plus/></button><Nav active={tab==='projects'} icon={<FolderKanban/>} label="פרויקטים" onClick={()=>setTab('projects')}/><Nav active={tab==='ai'} icon={<Sparkles/>} label="AI" onClick={()=>setTab('ai')}/></nav>
{add&&<div className="overlay" onClick={()=>setAdd(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="handle"/><h2>משימה חדשה</h2><label>מה צריך לעשות?</label><textarea autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="לדוגמה: לעשות בדיקה כלכלית לפרויקט חיפה"/><label>פרויקט</label><select value={pid} onChange={e=>setPid(+e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><div className="quick"><Clock size={17}/> יעד: היום</div><button className="primary" onClick={save}>הוסף משימה</button></div></div>}</div>}
function Section(p:{title:string;count:number;children:any}){return <section className="section"><div className="sectionTitle"><h2>{p.title}</h2><span>{p.count}</span></div>{p.children}</section>}
function TaskRow({t,projects,done}:{t:Task;projects:Project[];done:()=>void}){return <article className="task"><button className="check" onClick={done}/><div><strong>{t.title}</strong><span>{projects.find(p=>p.id===t.projectId)?.name}</span></div><em className={t.due==='באיחור'?'late':''}>{t.due}</em></article>}
function Nav({active,icon,label,onClick}:{active:boolean;icon:any;label:string;onClick:()=>void}){return <button className={active?'active':''} onClick={onClick}>{icon}<span>{label}</span></button>}